gymManageSys/gymManageSys/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from main import urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    # path('login/', auth_views.LoginView.as_view(), name="login"),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    # path('password_change/', auth_views.PasswordChangeView.as_view(template_name = "registration/password_change_form.html"), name ="password_change"),
    # path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name= "registration/password_change_done.html"), name= "password_done")
    path('accounts/', include('django.contrib.auth.urls'))


]

gymManageSys/main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.home, name='home'),
    path('pagedetail/<int:id>', views.page_detail, name="pagedetail"),
    path('faq', views.faq_list, name="faq"),
    path('contact_us', views.contact, name="contact_us"),
    path('enquiry', views.enquiry, name="enquiry"),
    path('gallery', views.showGallery, name="gallery"),
    path('gallerydetail/<int:id>', views.gallery_detail, name="gallery_detail"),
    path('pricing',views.pricing, name = "pricing"),
    path('signup',views.signup, name="signup"),
    path('checkout/<int:plan_id>', views.checkout, name = "checkout"),
    path('checkout_session/<int:plan_id>', views.checkout_session, name = "checkout_session"),
    path('pay_success', views.pay_success, name = "pay_success"),
    path('pay_cancel', views.pay_cancel, name = "pay_cancel"),
    #user dashboard session start
    path('user-dashboard', views.user_dashboard, name = "user_dashboard"),
    path('update-profile', views.update_profile, name = "update_profile"),
    #Trainer login
    path('trainerlogin', views.trainerlogin, name ="trainerlogin"),
    path('trainerlogout', views.trainerlogout, name ="trainerlogout"),
    path('trainer_dashboard', views.trainer_dashboard, name = "trainer_dashboard"),
    path('trainer_profile', views.trainer_profile, name = "trainer_profile"),
    path('trainer_subscribers', views.trainer_subscribers, name = "trainer_subscribers"),
    path('trainer_payments', views.trainer_payments, name = "trainer_payments"),
    path('trainer_changepassword', views.trainer_changepassword, name = "trainer_changepassword"),
    path('trainer_notifs', views.trainer_notifs, name = "trainer_notifs"),
    #notifications
    path('notifs', views.notifications, name="notifs"),
    path('get_notifs',views.get_notifs, name = "get_notifs"),
    path('mark_read_notif',views.mark_read_notif,name='mark_read_notif'),
    #Messages
    path('messages', views.trainer_msgs, name= "messages"),
    path('report_for_user',views.report_for_user,name='report_for_user'),
	path('report_for_trainer',views.report_for_trainer,name='report_for_trainer'),







    
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gymManageSys/main/models.py
from django.db import models
from django.utils.html import mark_safe
from django import forms
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
#Banners

class Banners(models.Model):
    img = models.ImageField(upload_to='banners/')
    alt_text = models.CharField(max_length = 150)
    
    def __str__(self) -> str:
        return self.alt_text
    def image_tag(self):
        return mark_safe('<img src="%s" width="80"/>'  % (self.img.url))
    

class Service(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    img = models.ImageField(upload_to="services/", null=True)

    def __str__(self) -> str:
        return self.title
    def image_tag(self):
        return mark_safe('<img src="%s" width="80"/>'  % (self.img.url))

    
#Pages model
    
class Page(models.Model):
    title= models.CharField(max_length=200)
    details = models.TextField()

    def __str__(self) -> str:
        return self.title

#FAQ model

class faq(models.Model):
    quest= models.TextField()
    ans = models.TextField()

    def __str__(self) -> str:
        return self.quest
    
#enquiry model

class Enquiry(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    details = models.TextField()
    send_time = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.full_name

#gallery model
class Gallery(models.Model):
    title = models.CharField(max_length=150)
    detail = models.TextField()
    img = models.ImageField(upload_to="gallery/", null=True)
    def __str__(self) -> str:
        return self.title
    def image_tag(self):
        return mark_safe('<img src="%s" width="80"/>'  % (self.img.url))

class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete = models.CASCADE,null=True)
    alt_text = models.CharField(max_length=150)
    detail = models.TextField()
    img = models.ImageField(upload_to="gallery_imgs/", null=True)
    def __str__(self) -> str:
        return self.alt_text
    def image_tag(self):
        return mark_safe('<img src="%s" width="80"/>'  % (self.img.url))
    
#subscription plan
class SubPlan(models.Model):
    title = models.CharField(max_length = 150)
    price = models.CharField(max_length = 50)
    max_member = models.IntegerField(null = True)
    highlight_status = models.BooleanField(default = False, null = True)
    validity_days = models.IntegerField(null = True)
    def __str__(self) -> str:
        return self.title
    
#subscrption plan feature
class SubPlanFeature(models.Model):
    # subplan = models.ForeignKey(SubPlan, on_delete = models.CASCADE)
    subplan = models.ManyToManyField(SubPlan)
    title = models.CharField(max_length = 150)

    
    def __str__(self) -> str:
        return self.title


#discount model
class PlanDiscount(models.Model):
    subplan = models.ForeignKey(SubPlan, on_delete =models.CASCADE, null = True)
    total_months = models.IntegerField()
    total_discount = models.IntegerField()

    def __str__(self) -> str:
        return str(self.total_months)
    
#subscriber model

class Subscriber(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE,null = True)
    mobile = models.CharField(max_length = 20)
    address = models.TextField()
    img = models.ImageField(upload_to="subs/")

    # def __str__(self) -> str:
    #     return self.user

    def image_tag(self):
        if self.img:
            return mark_safe('<img src="%s" width="80"/>'  % (self.img.url))
        else:
            return 'no-image'



@receiver(post_save,sender=User)
def create_subscriber(sender,instance, created,**kwargs):
    if created:
        Subscriber.objects.create(user=instance)
    


#subscription model
    
    
class Subscription(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE,null = True)
    plan = models.ForeignKey(SubPlan,on_delete = models.CASCADE,null = True)
    price = models.IntegerField()
    reg_date = models.DateField(auto_now_add = True, null = True)

   
#trainer model
class Trainer(models.Model):
    full_name = models.CharField(max_length = 100)
    username = models.CharField(max_length = 100, null = True)
    pwd = models.CharField(max_length = 100, null = True)
    mobile = models.CharField(max_length = 100)
    address = models.TextField()
    is_active = models.BooleanField(default = False)
    details = models.TextField()
    img = models.ImageField(upload_to="trainers/")
    instagram = models.CharField(max_length = 100, null = True)
    facebook = models.CharField(max_length = 100, null = True)
    salary = models.IntegerField(null = True)
    

    def __str__(self) -> str:
        return self.full_name
    
    def image_tag(self):
        return mark_safe('<img src="%s" width="80"/>'  % (self.img.url))
    

#notification

class Notify(models.Model):
    notify_detail = models.TextField()
    read_by_user = models.ForeignKey(User,on_delete = models.CASCADE, null = True, blank = True)
    read_by_trainer = models.ForeignKey(Trainer,on_delete = models.CASCADE, null = True, blank = True)

    
    def __str__(self) -> str:
        return self.notify_detail

#Mark as read notification by User
    
class NotifUserStatus(models.Model):
    notif = models.ForeignKey(Notify, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    status = models.BooleanField(default = False)


class AssignSubscriber(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)

	def __str__(self):
		return str(self.subscriber)


class TrainerSalary(models.Model):
	trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
	amt=models.IntegerField()
	amt_date=models.DateField()
	remarks=models.TextField(blank=True)

	class Meta:
		verbose_name_plural='Trainer Salary'

	def __str__(self):
		return str(self.trainer.full_name)
    
class TrainerNotification(models.Model):
    notif_msg = models.TextField()
    def __str__(self) -> str:
        return self.notif_msg
    
class NotifTrainerStatus(models.Model):
    notif = models.ForeignKey(TrainerNotification, on_delete = models.CASCADE)
    trainer = models.ForeignKey(Trainer, on_delete = models.CASCADE)
    status = models.BooleanField(default = False)

#Subscriber msg for trainer model
class TrainerMsg(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE)
    messages = models.TextField()
    class Meta:
        verbose_name_plural = "msg for trainers"

class TrainerSubscriberReport(models.Model):
    report_for_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True, related_name = "report_for_user")
    report_for_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE, null = True, related_name = "report_for_trainer")
    report_from_user=models.ForeignKey(User, on_delete=models.CASCADE,null=True, related_name = "report_from_user")
    report_from_trainer=models.ForeignKey(Trainer, on_delete=models.CASCADE, null = True, related_name = "report_from_trainer")
    report_msg = models.TextField()
    

class AppSetting(models.Model):
	logo_img=models.ImageField(upload_to='app_logos/')

	def image_tag(self):
		return mark_safe('<img src="%s" width="80" />' % (self.logo_img.url))

gymManageSys/main/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *

class EnquiryForm(forms.ModelForm):
    class Meta:
        model = Enquiry
        fields = ('full_name','email','details')

class SignUp(UserCreationForm):
    class Meta:
        model = User
        fields = ("first_name","last_name", "email", "username" ,"password1", "password2")

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("first_name","last_name", "email", "username")

class TrainerLoginForm(forms.ModelForm):
    class Meta:
        model = Trainer
        fields = ("username", "pwd")


class TrainerProfileForm(forms.ModelForm):
    class Meta:
        model = Trainer
        fields = ("full_name","mobile","details","img")

class TrainerChangePassword(forms.Form):
    old_password = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput())
    new_password = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput())

    
class ReportForTrainerForm(forms.ModelForm):
    class Meta:
        model = TrainerSubscriberReport
        fields = ('report_for_trainer', 'report_msg')


class ReportForUserForm(forms.ModelForm):
    class Meta:
        model = TrainerSubscriberReport
        fields = ('report_for_user', 'report_msg')

gymManageSys/main/templates/main/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <!-- jquery -->
    <script src="{%static 'jquery-3.7.1.min.js'%}"></script>
    <title>PITBULL FITNESS</title>
	
  </head>
  <body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
	  <div class="container">
	    <a class="navbar-brand" href="./">PITBULL FITNESS</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNav">
	      <ul class="navbar-nav ms-auto">
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="./">Home</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" aria-current="page" href="{% url 'gallery' %}">Gallery</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link" href="{% url 'pricing' %}">Pricing</a>
	        </li>
	        <li class="nav-item">
	          <a class="nav-link btn btn-sm btn-dark text-white" href="{% url 'enquiry' %}">Enquiry</a>
	        </li class="nav-item">
				{%if not request.user.is_authenticated%}
					{%if request.session.trainerLogin%}
					<li><a class="nav-link" href="{%url 'trainerlogout'%}">Trainer Logout</li>
					<li><a class="nav-link" href="{%url 'trainer_dashboard'%}">Dashboard</li>
					{%else%}
					<li><a class="nav-link" href="{% url 'trainerlogin'%}">Trainer Login</li>
					<li><a class="nav-link" href="{% url 'signup'%}">Register</a></li>
					<li><a class="nav-link" href="{% url 'login'%}">Login</a></li>
					{%endif%}
				{%else%}
	            <li><a class="nav-link" href="{% url 'user_dashboard' %}">Dashboard</a></li>
	            <li><a class="nav-link" href="{% url 'update_profile' %}">Profile</a></li>
	            <li><a class="nav-link" href="#">Settings</a></li>
				<li class="nav-link">
					<form method="post" action="{% url 'logout' %}">
						{% csrf_token %}
						<button class="btn btn-sm btn-dark text-white" type="submit">logout</button>
					</form>
				</li>
				{%endif%}
	        </li>
	      </ul>
	    </div>
	  </div>
	</nav>
    <!-- Header End -->
    {%block content%}

    {%endblock content%}


    <!--Footer Start-->
    <footer class="container py-5">
	    <p class="float-end"><a href="#">Back to top</a></p>
	    <p>© 2017–2021 Arnold GYM, Inc. · 
            <a href="{% url 'pagedetail' 2 %}">Privacy</a> · 
            <a href="{% url 'pagedetail' 1 %}">Terms</a> . 
            <a href="{% url 'faq' %}">FAQ</a> .
            <a href="{% url 'contact_us' %}" >Contact</a>
        </p>
	  </footer>

    <!-- Bootstrap Bundle -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
	<script type="text/javascript" src="{% static 'jquery-3.7.1.min.js' %}"></script>




  </body>
</html>

gymManageSys/main/templates/main/cancel.html
{%extends 'main/base.html'%}
{%block content%}
 <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Payment cancelled </h1>
            <h3>Please try again</h3>
		</section>
		<!-- End -->
    </main>
{%endblock content%}

gymManageSys/main/templates/main/checkout.html
{%extends 'main/base.html'%}
{% load static%}
{%block content%}
<main>
    <!-- Services -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">Checkout</h1>
            <table class="table table-bordered">
                <thead class="table-warning">
                    <tr>
                        <th>Plan</th>
                        <th>Plan Detail</th>
                        <th>Payment For</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <table class="table-bordered table">
                                <tr>
                                    <th>Name</th>
                                    <td>{{plan.title}}</td>
                                </tr>
                                <tr>
                                    <th>Price</th>
                                    <td>{{plan.price}}</td>
                                </tr>
                                <tr>
                                    <th>Max Member</th>
                                    <td>{{plan.max_member}}</td>
                                </tr>
                                <tr>
                                    <th>Already Registered</th>
                                    <td>15</td>
                                </tr>
                                <tr>
                                    <th>Balance Seats</th>
                                    <td>15</td>
                                </tr>
                            </table>
                        </td>
                        <td>
                            <ul class="list-unstyled">
                                {%for feature in plan.subplanfeature_set.all %}
                                <li>{{feature.title}}</li>
                                {%endfor%}
                            </ul>
                        </td>
                        <td>
                            <table class="table table-bordered">
                                {%for discount in plan.plandiscount_set.all %}
                                <tr>
                                    <td><input data-planprice="{{plan.price}}" data-discount="{{discount.total_discount}}" type="radio" id="validity1" name="validity" class="select-validity" value="{{discount.total_months}}" /></td>
                                    <th><label for="validity1">{{discount.total_months}} Month</label></th>
                                    <td>{{discount.total_discount}} %</td>
                                </tr>
                                {%endfor%}
                                
                            </table>
                        </td>
                    </tr>
                </tbody>
                <tfoot class="table-info">
                    <tr>
                        <td></td>
                        <th>Total Amount</th>
                        <td><b>RS<span class="totalAmount">{{plan.price}}</span></b></td>
                    </tr>
                    <tr>
                        <td colspan="2"></td>
                        <form method="post" action="{%url 'checkout_session' plan.id%}">
                        {%csrf_token%}
                        <td><input type="submit" value="Proceed to Payment" class="btn btn-primary" /></td>
                        </form>
                    </tr>
                </tfoot>
            </table>
    </section>
    <!-- End -->
</main>
<!-- End -->
{%endblock%}

<script type="text/javascript">
$(document).ready(function(){
    $(".select-validity").on('click',function(){
        var _planPrice=$(this).attr('data-planprice');
        var _planDisc=$(this).attr('data-discount');
        var _planValid=$(this).val();
        var _totalPrice=_planPrice*_planValid;
        if(_planDisc>0){
            var _discountedPrice=_totalPrice*_planDisc/100;
            _discountedPrice=_totalPrice-_discountedPrice;
        }else{
            var _discountedPrice=_totalPrice;
        }
        $(".totalAmount").text(_discountedPrice);
    });
});
</script>

gymManageSys/main/templates/main/contact_us.html
{% extends 'main/base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">Contact Us</h1>
			<div class="row">
				<div class="col-md-6">
					<table class="table table-bordered">
						<tr>
							<th>Address</th>
							<td>St-2, Goa</td>
						</tr>
						<tr>
							<th>Mobile</th>
							<td>+1 123456799</td>
						</tr>
						<tr>
							<th>Telephone</th>
							<td>123 7894562</td>
						</tr>
						<tr>
							<th>Email</th>
							<td>pitbullgym@example.com</td>
						</tr>
					</table>
				</div>
				<div class="col-md-6">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3845.2384860125485!2d73.84521297516932!3d15.471598985124578!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bbfbf57528e5b49%3A0xaa33c1fd1d138481!2sPitbull%20Gym!5e0!3m2!1sen!2sin!4v1711565241389!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

gymManageSys/main/templates/main/enquiry.html
{%extends 'main/base.html'%}
{% load static%}
{%block content%}
<main>
    <!-- Services -->
    <section class="container my-4">
        <h1 class="text-center mb-4 section-heading border-bottom pb-2">Enquiry Form</h1>
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'imgs/enquiry.jpg' %}" class="img-fluid" /> 
            </div>
            <div class="col-md-6">
                {% if msg %}
                    <p class="text-success">{{msg}}</p>
                {%endif%}
                <form method="post" action="{% url 'enquiry' %}">
                    {% csrf_token %}
                    <table class="table table-bordered">
                        {{form.as_table}}
                        <tr>
                            <td colspan="2">
                                <input type="submit" class="btn btn-primary" />
                            </td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </section>
    <!-- End -->
</main>
{%endblock%}

gymManageSys/main/templates/main/faq.html
{%extends 'main/base.html'%}
{%block content%}
 <main>
		<!-- Services -->
		<section class="container my-4">
			<h1 class="text-center mb-4 section-heading border-bottom pb-2">FAQ</h1>
            {% for f in faq %}
			<div class="accordion" id="accordionExample">
			<div class="accordion-item">
			    <h2 class="accordion-header" id="headingOne">
			      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
			        {{f.quest}}
			      </button>
			    </h2>
			    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
			      <div class="accordion-body">
			        <strong>{{f.ans}}</strong>
			      </div>
			    </div>
            </div>  
			</div>
            {% endfor %}
		</section>
		<!-- End -->
    </main>
{%endblock content%}

gymManageSys/main/templates/main/pricing.html
{%extends 'main/base.html'%}
{%block content%}
{%load static%}
{%load check_package%}
{% load mathfilters %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-icons/font/bootstrap-icons.css'%}" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">


<section class="container my-4">
    <h1 class="text-center mb-4 section-heading border-bottom pb-2">Plans</h1>
<main>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
  {%for plan in plans%}
  <div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
      {% if plan.highlight_status  %}
      <div class="card-header py-3 text-white bg-primary border-primary"> 
      {%else%}
      <div class="card-header py-3">
      {%endif%}
        <h4 class="my-0 fw-normal">{{plan.title}}</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">{{plan.price}}RS<small class="text-muted fw-light">/yr</small></h1>
        <p class="text-success">Maximum members capacity {{plan.max_member|sub:plan.total_members}}</p>
        <ul class="list-unstyled mt-3 mb-4">
          {%for feature in plan.subplanfeature_set.all %}
          <li>{{feature.title}}</li>
          {%endfor%}
        </ul>
        {% if request.user.is_authenticated %}
          {% check_user_package request.user.id plan.id as check_pckg %}
          {% check_pckg_validity request.user.id plan.id as check_validity %}

          {% if check_pckg %}
            {% if check_validity %}
              <a href="{% url 'checkout' plan.id %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
            {% else %}
              <a href="#" class="w-100 btn btn-lg btn-dark disabled">Purchased</a>
            {% endif %}
          {% else %}
          <a href="{% url 'checkout' plan.id %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
          {% endif %}
          
          {% else %}
          <a href="{% url 'login' %}" class="w-100 btn btn-lg btn-outline-primary">Get started</a>
          {% endif %}
      </div>
    </div>
  </div>
  {%endfor%}
</div>

<h2 class="display-6 text-center mb-4">Compare plans</h2>

<div class="table-responsive">
  <table class="table text-center">
    <thead>
      <tr>
        <th style="width: 34%;"></th>
        {%for plan in plans%}
        <th style="width: 22%;">{{plan.title}}</th>
        {%endfor%}
      </tr>
    </thead>
    <tbody>
      {%for feature in dfeature%}

      <tr>
        <th scope="row" class="text-start">{{feature.title}}</th>
        {%for plan in plans%}
        <td>
            {%if plan in feature.subplan.all %}
            <i class="bi bi-check-lg"></i>
            {%else%}
            <i class="bi bi-x-lg text-danger"></i>
            {%endif%}

        </td>
        {%endfor%}
      </tr>
      {%endfor%}
    </tbody>
  </table>
</div>
</main>
</section>

{%endblock%}